In [7]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [8]:
cd ~/demres

/Users/zurfarosa/demres

In [27]:
import os, sys, re

module_path = os.path.abspath(os.path.join('..'))
if module_path not in sys.path:
    sys.path.append(module_path)

import pandas as pd
from datetime import date, timedelta

import demres
from demres.common import codelists,druglists

In [10]:
pd.set_option('display.max_columns', None)

In [11]:
codelists

In [16]:
condition_df = pd.DataFrame(columns=['code','coding_system','description'])

In [17]:
condition_df

Empty DataFrame
Columns: [code, coding_system, description]
Index: []

In [26]:
for row,code in enumerate(codelists.epilepsy['codes']):
    condition_df.loc[row,'code']=code
    condition_df.loc[row,'description']=code

[autoreload of demres.common.codelists failed: Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/IPython/extensions/autoreload.py", line 247, in check
    superreload(m, reload, self.old_objects)
  File "/Users/zurfarosa/demres/common/codelists.py", line 1889
    'F257.00':'Kojevnikov's epilepsy',
                          ^
SyntaxError: invalid syntax
]

In [24]:
condition_df

        code coding_system description
0       1473           NaN         NaN
1    1B1W.00           NaN         NaN
2    1O30.00           NaN         NaN
3       2823           NaN         NaN
4       2824           NaN         NaN
5    2824.11           NaN         NaN
6       2825           NaN         NaN
7       2828           NaN         NaN
8    667B.00           NaN         NaN
9    667N.00           NaN         NaN
10   Eu05212           NaN         NaN
11   Eu05y11           NaN         NaN
12   Eu06013           NaN         NaN
13   F132100           NaN         NaN
14   F132200           NaN         NaN
15   F25..00           NaN         NaN
16   F250.00           NaN         NaN
17   F250000           NaN         NaN
18   F250011           NaN         NaN
19   F250100           NaN         NaN
20   F250200           NaN         NaN
21   F250300           NaN         NaN
22   F250y00           NaN         NaN
23   F250z00           NaN         NaN
24   F251.00           NaN         NaN
25   F251000           NaN         NaN
26   F251011           NaN         NaN
27   F251200           NaN         NaN
28   F251300           NaN         NaN
29   F251400           NaN         NaN
..       ...           ...         ...
52   F255311           NaN         NaN
53   F255400           NaN         NaN
54   F255500           NaN         NaN
55   F255600           NaN         NaN
56   F255y00           NaN         NaN
57   F255z00           NaN         NaN
58   F256100           NaN         NaN
59   F256.11           NaN         NaN
60   F257.00           NaN         NaN
61   F259.11           NaN         NaN
62   F25B.00           NaN         NaN
63   F25C.00           NaN         NaN
64   F25D.00           NaN         NaN
65   F25E.00           NaN         NaN
66   F25F.00           NaN         NaN
67   F25X.00           NaN         NaN
68   F25y.00           NaN         NaN
69   F25y000           NaN         NaN
70   F25y100           NaN         NaN
71   F25y200           NaN         NaN
72   F25y300           NaN         NaN
73   F25yz00           NaN         NaN
74   F25z.00           NaN         NaN
75  F25.z.11           NaN         NaN
76   Fyu5000           NaN         NaN
77   Fyu5100           NaN         NaN
78   Fyu5200           NaN         NaN
79   Fyu5900           NaN         NaN
80   SC20000           NaN         NaN
81   ZS82.00           NaN         NaN

[82 rows x 3 columns]