In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
cd ~/demres

/Users/zurfarosa/demres

In [3]:
from IPython.core.display import display, HTML
display(HTML("<style>.container { width:95% !important; }</style>"))

In [4]:
import os
import sys
from pprint import pprint

import pandas as pd
import numpy as np
from datetime import date, timedelta
import re

module_path = os.path.abspath(os.path.join('..'))
if module_path not in sys.path:
    sys.path.append(module_path)

import demres
from demres.common.constants import entry_type
from demres.common import codelists,druglists
from demres.common import helper_functions
from demres.common.process_raw_data import *
from demres.dempred.constants import Study_Design
from dempred.functions import *

In [5]:
# pt_features

In [6]:
# pegprod = pd.read_csv('data/dicts/proc_pegasus_prod.csv', delimiter=',')

In [7]:
# pegprod[pegprod['substance strength']=='2mg + 10mg']

In [79]:
pt_features = pd.read_csv('data/pt_data/processed_data/pt_features_dempred.csv',delimiter=',')

In [80]:
# helper_functions.backup('data/pt_data/processed_data','pt_features_dempred.csv')

In [81]:
pt_features = get_total_prescriptions(pt_features)

In [82]:
pt_features

,patid,gender,yob,pracid,index_date,isCase,final dementia medcode,data_start,data_end,matchid,mood_stabilisers_pdds,sedatives_pdds,fgas_pdds,sgas_pdds,fga_depots_pdds,antidepressants_pdds,nsaids_pdds,psych_prescription_count,nonpsych_prescription_count
0,4307419,2,1910,419,2002-09-10,True,1917.0,1999-09-01,2002-09-11,62131.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,12189179,1,1926,179,2000-02-18,True,1917.0,1997-02-03,2000-02-18,27033.0,NaN,NaN,41.74,NaN,NaN,NaN,131.20,1.0,27.0
2,15431564,1,1917,564,2004-10-04,True,4693.0,2001-09-18,2004-10-06,81847.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,23369263,2,1920,263,2009-06-04,True,6578.0,2006-05-12,2009-06-08,40783.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,92.0
4,15203047,2,1926,47,2005-11-12,True,1916.0,2002-10-14,2005-11-14,6796.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,260.0
5,3825320,1,1917,320,2003-07-10,True,1350.0,2000-06-28,2003-08-01,48531.0,NaN,NaN,697.96,NaN,NaN,NaN,NaN,20.0,144.0
6,13223179,2,1905,179,2002-03-19,True,1916.0,1999-03-02,2002-04-05,27038.0,NaN,456.51,NaN,234.60,NaN,NaN,NaN,42.0,7.0
7,10613282,2,1919,282,2003-12-18,True,4693.0,2000-11-28,2004-01-05,42848.0,610.68,478.93,187.85,NaN,NaN,NaN,NaN,45.0,121.0
8,23999190,2,1924,190,2012-01-02,True,4693.0,2008-12-11,2012-01-19,28764.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,250.0
9,50271229,1,1910,229,2000-07-28,True,1917.0,1997-06-19,2000-07-28,35251.0,765.45,596.55,NaN,NaN,NaN,NaN,193.20,17.0,168.0
10,21385409,2,1910,409,2009-10-02,True,1350.0,2006-08-29,2009-10-08,60887.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,15199456,2,1917,456,2008-05-09,True,1350.0,2005-03-29,2008-05-09,67818.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,5946124,2,1928,124,2001-06-15,True,7664.0,1998-05-08,2001-06-21,17646.0,NaN,NaN,29.82,NaN,NaN,NaN,NaN,1.0,27.0
13,3828320,2,1907,320,2003-08-06,True,1350.0,2000-06-28,2003-08-14,48532.0,NaN,NaN,NaN,313.60,NaN,167.17,NaN,11.0,152.0
14,24585320,2,1916,320,2009-01-21,True,4693.0,2005-12-28,2009-02-12,48814.0,NaN,6.72,NaN,NaN,NaN,NaN,NaN,1.0,226.0
15,24390310,2,1920,310,2011-03-23,True,6578.0,2008-03-12,2011-05-03,47049.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,30.0
16,12940614,2,1918,614,2005-10-24,True,1916.0,2002-10-07,2005-11-28,86163.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,5551458,2,1917,458,2008-01-24,True,1916.0,2005-01-24,2008-03-20,68237.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,7725398,2,1914,398,2000-12-03,True,4693.0,1997-11-28,2001-01-25,58938.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,5176384,1,1918,384,2002-12-19,True,8634.0,1999-10-22,2002-12-19,57229.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,29125431,2,1918,431,2012-03-04,True,6578.0,2009-01-06,2012-03-08,63723.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,10638289,1,1927,289,2011-06-03,True,1350.0,2008-06-03,2011-08-04,44189.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,4341471,1,1915,471,2000-01-18,True,7323.0,1996-11-22,2000-01-25,70953.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,3135241,2,1915,241,2002-12-27,True,1916.0,1999-12-08,2003-02-10,36519.0,NaN,NaN,293.13,NaN,NaN,NaN,NaN,7.0,220.0
24,556503,2,1923,503,2010-08-20,True,6578.0,2007-08-14,2010-10-18,75862.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,25369256,2,1917,256,2011-02-22,True,1350.0,2007-12-17,2011-03-01,39603.0,NaN,NaN,NaN,NaN,NaN,2309.47,NaN,45.0,167.0
26,7061435,2,1904,435,2002-12-02,True,9509.0,1999-09-29,2002-12-13,64078.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,2943480,1,1920,480,2004-06-02,True,4693.0,2001-03-23,2004-06-07,72198.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,6090306,2,1909,306,2002-10-15,True,1350.0,1999-08-06,2002-10-21,46225.0,NaN,NaN,NaN,NaN,NaN,NaN,204.13,NaN,458.0
29,10394377,1,1915,377,2004-05-22,True,1916.0,2001-04-01,2004-06-17,55939.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,10643476,1,1909,476,2002-11-14,True,7664.0,1999-09-16,2002-12-02,71747.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,26681247,2,1914,247,2000-04-28,True,1350.0,1997-04-11,2000-06-28,37930.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,217.0
32,124416,2,1911,416,2000-12-01,True,1350.0,1997-10-26,2001-01-12,61723.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,3366025,2,1920,25,2003-06-24,True,4693.0,2000-04-27,2003-07-16,4046.0,NaN,108.78,NaN,675.44,NaN,NaN,NaN,9.0,119.0
34,19266355,1,1920,355,2008-12-04,True,1917.0,2005-11-30,2009-02-17,53324.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,17997322,2,1921,322,2005-07-24,True,4693.0,2002-05-30,2005-08-18,49245.0,NaN,1295.76,6544.11,2316.85,NaN,NaN,NaN,113.0,396.0
36,10223226,2,1912,226,2004-04-21,True,1917.0,2001-01-30,2004-04-21,34619.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,207.0
37,12859614,2,1918,614,2005-10-24,True,1916.0,2002-09-05,2005-11-28,86162.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,1318593,1,1927,593,2011-07-28,True,27677.0,2008-06-25,2011-09-19,84469.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39,3910375,1,1920,375,2005-06-01,True,1350.0,2002-04-24,2005-07-18,55758.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40,17763223,2,1910,223,2002-02-21,True,1350.0,1999-01-25,2002-04-22,34082.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,51.0
41,7380416,2,1909,416,2000-12-27,True,1350.0,1997-10-26,2001-01-23,61868.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
42,17534251,1,1914,251,2007-01-03,True,4693.0,2003-12-30,2007-03-29,38542.0,NaN,NaN,NaN,NaN,NaN,1370.25,NaN,38.0,171.0
43,10570245,1,1925,245,2005-05-26,True,1917.0,2002-03-14,2005-06-16,37435.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22.0
44,5066173,1,1926,173,2005-09-19,True,7664.0,2002-06-25,2005-09-28,25856.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,19.0
45,7782260,2,1921,260,2004-11-12,True,1350.0,2001-08-21,2004-11-29,40285.0,NaN,513.86,41.74,NaN,NaN,32.27,NaN,22.0,72.0
46,4781131,1,1914,131,2003-05-23,True,6578.0,2000-04-04,2003-07-14,19397.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,128.0
47,15344251,2,1920,251,2004-10-07,True,1350.0,2001-07-03,2004-10-13,38530.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,117.0
48,7756014,1,1922,14,2001-07-10,True,1350.0,1998-06-26,2001-10-08,2439.0,NaN,NaN,NaN,NaN,NaN,NaN,371.51,NaN,33.0
49,4953066,2,1911,66,2002-12-19,True,1917.0,1999-12-13,2003-03-27,8589.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22.0
50,29013263,2,1919,263,2009-12-16,True,4693.0,2006-10-10,2010-01-22,40821.0,NaN,NaN,NaN,NaN,NaN,919.61,NaN,110.0,993.0
51,12072361,2,1921,361,2004-11-22,True,4693.0,2001-10-16,2005-02-01,53993.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
52,1764470,2,1910,470,2000-03-15,True,8634.0,1997-01-28,2000-05-16,70204.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
53,1031266,2,1916,266,2003-08-31,True,1917.0,2000-05-31,2003-09-17,41054.0,NaN,NaN,NaN,1.03,NaN,NaN,NaN,3.0,204.0
54,4380408,2,1916,408,2006-03-28,True,7323.0,2003-01-14,2006-05-03,60512.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
55,20142366,2,1912,366,2001-03-02,True,1350.0,1997-11-13,2001-03-02,54941.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
56,17895310,2,1910,310,2003-11-14,True,6578.0,2000-07-26,2003-11-14,47026.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,121.0
57,22529001,2,1914,1,2008-01-25,True,6578.0,2004-10-06,2008-01-25,206.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,545.0
58,11564372,1,1916,372,2006-12-01,True,6578.0,2003-11-04,2007-02-24,55388.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
59,19719310,2,1925,310,2006-01-06,True,1917.0,2002-09-16,2006-01-06,47032.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,96.0
60,128476,1,1909,476,2002-12-21,True,1916.0,1999-09-16,2003-01-08,71558.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
61,18058166,1,1914,166,2003-05-18,True,4693.0,2000-04-10,2003-08-04,25077.0,NaN,68.20,591.03,NaN,NaN,NaN,NaN,8.0,296.0
62,26350263,1,1933,263,2009-05-21,True,9509.0,2006-05-12,2009-09-04,40811.0,NaN,NaN,NaN,NaN,NaN,580.81,NaN,21.0,143.0
63,5659328,1,1923,328,2004-09-08,True,1350.0,2001-06-04,2004-09-28,49865.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
64,10939564,2,1913,564,2005-01-13,True,7323.0,2001-09-18,2005-01-14,81762.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
65,22883320,2,1914,320,2008-04-28,True,4693.0,2005-01-24,2008-05-23,48811.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,110.0
66,5997643,2,1946,643,2011-07-13,True,49263.0,2008-07-03,2011-11-02,89847.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
67,678598,2,1912,598,2003-04-09,True,1350.0,1999-12-09,2003-04-09,84897.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
68,9494234,2,1920,234,2004-03-03,True,1917.0,2000-11-02,2004-03-04,35797.0,NaN,NaN,6250.76,NaN,NaN,NaN,NaN,2.0,2.0
69,22509396,2,1922,396,2007-11-14,True,1917.0,2004-09-22,2008-01-24,58689.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
70,9038206,2,1918,206,2002-05-29,True,1916.0,1999-04-20,2002-08-22,31797.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0
71,19664017,2,1914,17,2001-09-05,True,1350.0,1998-07-13,2001-11-14,2898.0,NaN,392.00,292.20,578.95,NaN,292.75,796.41,31.0,175.0
72,12779458,1,1934,458,2008-02-03,True,6578.0,2005-01-24,2008-05-29,68407.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
73,29225424,1,1933,424,2011-03-08,True,6578.0,2008-02-14,2011-06-22,62610.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
74,9176024,2,1906,24,2001-03-09,True,1917.0,1997-10-31,2001-03-09,3887.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,51.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
69407,1456013,1,1913,13,2000-05-03,False,NaN,1995-07-28,2013-05-08,2230.0,NaN,NaN,NaN,NaN,NaN,NaN,1741.76,NaN,51.0
69408,1474038,1,1927,38,2006-01-01,False,NaN,1995-07-30,2013-05-10,5756.0,NaN,1418.16,NaN,NaN,NaN,NaN,410.06,26.0,244.0
69409,3505038,1,1931,38,2009-06-16,False,NaN,1995-07-30,2013-05-10,5557.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
69410,6616013,1,1925,13,2006-08-10,False,NaN,1995-07-28,2013-05-09,2175.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
69411,22581013,2,1932,13,2011-03-08,False,NaN,1995-07-28,2013-05-09,2142.0,NaN,NaN,NaN,NaN,NaN,14.37,46.65,1.0,147.0
69412,9342013,1,1933,13,2009-12-21,False,NaN,1995-07-28,2013-05-10,2288.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,91.0
69413,10100013,1,1931,13,2004-11-26,True,8634.0,1995-07-28,2013-05-10,2185.0,NaN,NaN,NaN,NaN,NaN,2034.38,NaN,21.0,101.0
69414,15439013,1,1932,13,2011-04-28,True,42279.0,1995-07-28,2013-05-10,2243.0,NaN,NaN,29.82,NaN,NaN,144.69,62.21,6.0,71.0
69415,4205013,2,1926,13,2007-11-30,True,42279.0,1995-07-28,2013-05-13,2110.0,NaN,21.04,NaN,NaN,NaN,1864.64,NaN,23.0,61.0
69416,1590013,2,1916,13,2001-04-10,True,4357.0,1995-07-28,2013-05-13,2069.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,37.0
69417,3132013,2,1926,13,2011-07-01,True,6578.0,1995-07-28,2013-05-13,2092.0,NaN,NaN,278.29,NaN,NaN,NaN,NaN,10.0,80.0
69418,3718013,2,1923,13,2009-04-15,False,NaN,1995-07-28,2013-05-13,2203.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
69419,19617013,1,1936,13,2010-08-18,True,42602.0,1995-07-28,2013-05-13,2306.0,NaN,NaN,NaN,NaN,NaN,NaN,297.70,NaN,19.0
69420,18897013,1,1938,13,2011-01-19,False,NaN,1995-07-28,2013-05-13,2211.0,NaN,NaN,NaN,NaN,NaN,NaN,435.44,NaN,87.0
69421,9461013,2,1941,13,2011-06-14,False,NaN,1995-07-28,2013-05-14,2364.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.0
69422,10767013,2,1927,13,2005-11-29,False,NaN,1995-07-28,2013-05-14,2171.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
69423,10724013,1,1928,13,2007-01-02,False,NaN,1995-07-28,2013-05-14,2378.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,102.0
69424,8983013,2,1932,13,2012-03-21,False,NaN,1995-07-28,2013-05-14,2274.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
69425,13155013,2,1924,13,2006-01-24,True,1917.0,1995-07-28,2013-05-14,2225.0,NaN,NaN,NaN,NaN,NaN,NaN,1351.17,NaN,94.0
69426,18944013,2,1922,13,2006-05-08,True,8634.0,1995-07-28,2013-05-14,2297.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,52.0
69427,367013,2,1930,13,2011-01-07,False,NaN,1995-07-28,2013-05-14,2349.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
69428,4847013,1,1935,13,2010-03-24,False,NaN,1995-07-28,2013-05-14,2316.0,NaN,NaN,NaN,NaN,NaN,NaN,62.21,NaN,101.0
69429,1917013,2,1920,13,2006-04-19,False,NaN,1995-07-28,2013-05-14,2272.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
69430,14287013,2,1936,13,2011-11-08,True,19477.0,1995-07-28,2013-05-15,2233.0,NaN,NaN,532.73,NaN,NaN,1976.24,NaN,37.0,324.0
69431,19183013,2,1924,13,2005-03-29,True,11175.0,1995-07-28,2013-05-15,2298.0,NaN,NaN,NaN,241.23,NaN,531.53,NaN,13.0,72.0
69432,11999013,2,1926,13,2011-07-01,False,NaN,1995-07-28,2013-05-15,2092.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
69433,16355013,1,1936,13,2010-08-18,False,NaN,1995-07-28,2013-05-15,2306.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
69434,4518013,2,1928,13,2012-02-21,False,NaN,1995-07-28,2013-05-16,2370.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
69435,7047013,1,1924,13,2011-05-29,False,NaN,1995-07-28,2013-05-16,2246.0,NaN,1.67,NaN,NaN,NaN,NaN,155.51,1.0,58.0
69436,18570013,2,1927,13,2011-02-02,True,6578.0,1995-07-28,2013-05-16,2292.0,NaN,NaN,NaN,NaN,NaN,28.73,NaN,1.0,41.0
69437,2669013,1,1924,13,2010-05-17,False,NaN,1995-07-28,2013-05-16,2058.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
69438,1359013,2,1927,13,2006-10-31,False,NaN,1995-07-28,2013-05-17,2228.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
69439,11312013,2,1923,13,2009-04-15,True,8634.0,1995-07-28,2013-05-17,2203.0,NaN,NaN,NaN,NaN,NaN,1782.86,NaN,39.0,325.0
69440,15930013,1,1932,13,2011-04-28,False,NaN,1995-07-28,2013-05-17,2243.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
69441,16130013,2,1920,13,2009-01-27,False,NaN,1995-07-28,2013-05-17,2151.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
69442,1437013,1,1929,13,2006-06-07,False,NaN,1995-07-28,2013-05-17,2101.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
69443,8248013,2,1931,13,2011-10-21,True,1917.0,1995-07-28,2013-05-17,2163.0,NaN,NaN,667.89,NaN,NaN,619.34,100.88,18.0,103.0
69444,5497013,1,1931,13,2004-11-26,False,NaN,1995-07-28,2013-05-17,2185.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
69445,1880013,2,1921,13,2004-08-26,False,NaN,1995-07-28,2013-05-17,2093.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
69446,4889488,2,1913,488,2000-04-21,False,NaN,1995-02-17,2013-02-25,73722.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
69447,14646488,2,1939,488,2009-07-16,False,NaN,1995-02-17,2013-03-10,73677.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
69448,6774488,1,1937,488,2008-01-22,False,NaN,1995-02-17,2013-03-22,73681.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
69449,5650488,1,1939,488,2012-01-23,True,1917.0,1995-02-17,2013-03-26,73684.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
69450,10531488,2,1927,488,2006-11-15,True,8195.0,1995-02-17,2013-04-04,73695.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
69451,11262488,1,1931,488,2011-11-09,True,6578.0,1995-02-17,2013-04-05,73701.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
69452,10854488,2,1923,488,2011-10-10,False,NaN,1995-02-17,2013-04-05,73725.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
69453,2546488,2,1939,488,2009-07-16,True,7664.0,1995-02-17,2013-04-06,73677.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
69454,12938488,1,1934,488,2006-08-14,True,8634.0,1995-02-17,2013-04-08,73704.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
69455,15195488,1,1939,488,2009-02-15,True,1916.0,1995-02-17,2013-04-12,73711.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
69456,8580488,1,1931,488,2011-11-09,False,NaN,1995-02-17,2013-04-15,73701.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
69457,10620488,2,1929,488,2012-01-25,False,NaN,1995-02-17,2013-04-15,73721.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
69458,13292488,1,1925,488,2006-05-17,False,NaN,1995-02-17,2013-04-16,73726.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
69459,16116488,2,1935,488,2002-07-02,False,NaN,1995-02-17,2013-04-16,73700.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
69460,17517488,1,1939,488,2012-01-23,False,NaN,1995-02-17,2013-04-17,73684.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
69461,2194488,2,1926,488,2003-08-03,True,1916.0,1995-02-17,2013-04-17,73676.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
69462,16606488,1,1942,488,2012-04-12,False,NaN,1995-02-17,2013-04-17,73687.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
69463,16816488,2,1922,488,2010-01-01,True,1916.0,1995-02-17,2013-04-17,73715.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
69464,2053336,1,1942,336,2009-05-05,False,NaN,1994-12-10,2013-02-22,50913.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
69465,1091336,2,1927,336,2010-04-20,False,NaN,1994-12-10,2013-03-05,50930.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
69466,1701336,1,1923,336,2009-01-19,False,NaN,1994-12-09,2013-03-28,50901.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
69467,1421336,1,1930,336,2011-09-26,True,8195.0,1994-12-09,2013-04-24,50904.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
69468,1562336,2,1920,336,2008-10-08,False,NaN,1994-12-09,2013-04-25,50892.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
69469,755336,2,1938,336,2012-01-19,True,1917.0,1994-12-09,2013-05-02,50891.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
69470,1503336,1,1930,336,2011-07-25,False,NaN,1994-12-09,2013-05-07,50945.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
69471,2297336,1,1930,336,2011-09-26,False,NaN,1994-12-09,2013-05-07,50904.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
69472,1130336,2,1938,336,2012-01-19,False,NaN,1994-12-10,2013-05-09,50891.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
69473,1716336,2,1921,336,2007-07-31,False,NaN,1994-12-09,2013-05-09,50883.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
69474,1188336,1,1938,336,2012-05-09,False,NaN,1994-12-09,2013-05-13,50881.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
69475,1737336,1,1942,336,2009-05-05,True,1917.0,1994-12-09,2013-05-14,50913.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
69476,1220336,2,1928,336,2010-12-08,False,NaN,1994-12-09,2013-05-15,50925.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
69477,1497336,2,1928,336,2011-07-11,False,NaN,1994-12-09,2013-05-16,50924.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
69478,715336,2,1930,336,2008-09-04,False,NaN,1994-12-09,2013-05-20,50882.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
69479,1033336,1,1928,336,2008-11-21,False,NaN,1994-12-09,2013-05-21,50938.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
69480,136336,1,1938,336,2012-05-09,True,1350.0,1994-12-09,2013-05-21,50881.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
69481,775336,2,1920,336,2008-10-08,True,1350.0,1994-12-09,2013-05-21,50892.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [83]:
pt_features.to_csv('data/pt_data/processed_data/pt_features_dempred.csv',index=False)