In [1]:
%load_ext autoreload
%autoreload 1

In [2]:
%aimport data_processing.my_functions
%aimport codelists
%aimport constants
%aimport import_file

In [3]:
from data_processing import *

In [4]:
from import_file import *

In [5]:
pd.options.display.max_rows = 1000

In [6]:
medcoded_entries = pd.read_csv('data/pt_data/medcoded_entries.csv',delimiter=',',parse_dates=['eventdate'],infer_datetime_format=True)

In [29]:
medcoded_entries.sample(5)

             patid  eventdate     sysdate  medcode  type
44104694  19763381 2011-02-25  2011-02-26    14372     3
27608487   4953662 2008-05-14  2008-05-21       31     2
273345     5670003 2006-06-19  2006-06-19     8297     2
37924453   7422226 2005-04-19  2005-04-20       17     3
6865423    6096155 2010-10-04  2010-10-04       26     2

In [30]:
insomnia_medcodes = get_medcodes_from_readcodes(codelists.insomnia_readcodes)

In [31]:
insom_events = medcoded_entries[medcoded_entries['medcode'].isin(insomnia_medcodes)]

In [32]:
insom_events.sample(5)

            patid  eventdate     sysdate  medcode  type
5971225   5862133 2011-09-29  2011-09-29     4537     2
18198632  4096407 2008-02-21  2008-02-21     4537     2
5775076   6515127 2011-08-05  2011-08-05     4537     2
3423075   1565084 2003-06-03  2003-06-03     4537     2
20073559   235449 1992-07-15  2009-02-20      750     2

In [33]:
insom_events = insom_events[pd.notnull(insom_events['eventdate'])] #drops a small number of rows (only about 64) with NaN eventdates

In [34]:
insom_events = insom_events[['patid','eventdate']].set_index('eventdate').groupby('patid').resample('M').count()

In [35]:
insom_events.head(10)

                  patid
patid eventdate
1467  2007-11-30      2
      2007-12-31      0
      2008-01-31      2
      2008-02-29      2
      2008-03-31      0
      2008-04-30      0
      2008-05-31      0
      2008-06-30      1
      2008-07-31      0
      2008-08-31      0

In [36]:
#convert group_by object back to dataframe
insom_events = insom_events.add_suffix('_count').reset_index()

In [37]:
insom_events.columns=['patid','eventdate','insom_count']
#delete zero counts

In [38]:
insom_events = insom_events[insom_events['insom_count']>0]

In [39]:
insom_events

           patid  eventdate  insom_count
0           1467 2007-11-30            2
2           1467 2008-01-31            2
3           1467 2008-02-29            2
7           1467 2008-06-30            1
18          1467 2009-05-31            1
22          1467 2009-09-30            1
64          1467 2013-03-31            1
65          3432 2004-12-31            1
112         3432 2008-11-30            1
113         3549 2005-10-31            1
116         3549 2006-01-31            1
121         3549 2006-06-30            1
138         3549 2007-11-30            1
139         4290 2005-06-30            1
140         6365 2008-05-31            1
141         9609 2006-05-31            1
142        12043 1990-02-28            1
143        12137 2008-06-30            1
144        13638 2003-05-31            1
145        14280 2004-10-31            1
162        14280 2006-03-31            1
174        14280 2007-03-31            1
181        14280 2007-10-31            1
246        14280 2013-03-31            1
247        15385 1993-04-30            1
308        15385 1998-05-31            1
309        16064 2006-06-30            1
310        17267 2011-09-30            1
311        18255 1997-12-31            1
312        18571 2004-10-31            1
313        20172 2006-10-31            1
314        20285 2008-11-30            1
315        20581 2008-01-31            1
316        21132 1989-11-30            1
564        21132 2010-07-31            2
565        22638 2008-06-30            1
566        24081 1991-03-31            1
641        24081 1997-06-30            1
642        24436 2012-02-29            1
643        25420 1999-10-31            1
644        25570 2011-04-30            1
645        26002 2008-11-30            1
646        26132 2004-03-31            1
647        26330 2007-06-30            1
648        27025 2001-08-31            1
649        27052 2009-06-30            1
665        27052 2010-10-31            1
666        27571 2010-11-30            1
676        27571 2011-09-30            1
677        28218 1999-07-31            1
678        28218 1999-08-31            1
679        28290 2008-10-31            1
680        29551 2003-09-30            1
681        30279 2011-01-31            1
682        30571 2010-01-31            1
683        32504 2002-10-31            1
684        36624 2006-05-31            1
685        37099 2001-04-30            1
686        39463 1989-01-31            1
739        39463 1993-06-30            1
764        39463 1995-07-31            1
777        39463 1996-08-31            1
812        39463 1999-07-31            1
814        39463 1999-09-30            1
833        39463 2001-04-30            1
877        39463 2004-12-31            1
912        39463 2007-11-30            4
913        39463 2007-12-31            1
916        39463 2008-03-31            1
917        39598 2008-07-31            1
918        40139 2007-12-31            1
919        40139 2008-01-31            2
921        40139 2008-03-31            1
922        40139 2008-04-30            1
924        40139 2008-06-30            1
925        40334 1998-07-31            1
972        40334 2002-06-30            1
975        40334 2002-09-30            1
976        40557 2005-05-31            1
1014       40557 2008-07-31            1
1048       40557 2011-05-31            1
1049       41236 1988-01-31            1
1085       41236 1991-01-31            1
1086       41271 2012-11-30            1
1087       43045 1991-01-31            1
1088       43624 2009-02-28            1
1089       44447 1996-10-31            1
1101       44447 1997-10-31            1
1163       44447 2002-12-31            1
1225       44447 2008-02-29            1
1228       44447 2008-05-31            1
1229       44654 2008-01-31            1
1230       45315 2003-07-31            1
1231       45538 2001-06-30            1
1232       45571 2008-02-29            1
1233       47444 2003-09-30            1
1234       49415 1991-07-31            1
1235       50159 2005-07-31            1
1254       50159 2007-02-28            1
1255       51650 2006-12-31            1
1256       52102 1988-02-29            1
1300       52102 1991-10-31            1
1312       52102 1992-10-31            1
1313       52416 2006-07-31            1
1314       52511 1991-02-28            1
1320       52511 1991-08-31            2
1322       52511 1991-10-31            1
1330       52511 1992-06-30            1
1332       52511 1992-08-31            1
1333       52511 1992-09-30            1
1334       54132 1994-11-30            1
1335       55033 2004-07-31            1
1336       55128 1984-01-31            1
1470       55128 1995-03-31            1
1471       55533 2011-09-30            1
1472       56230 1996-04-30            1
1473       57339 1990-04-30            1
1474       57392 1992-08-31            1
1475       58002 2005-11-30            1
1476       58032 2002-05-31            1
1477       58388 1991-03-31            1
1478       58466 1993-05-31            1
1479       59360 2004-07-31            1
1480       59360 2004-08-31            1
1494       59360 2005-10-31            1
1505       59360 2006-09-30            1
1518       59360 2007-10-31            1
1530       59360 2008-10-31            1
1542       59360 2009-10-31            1
1554       59360 2010-10-31            1
1555       59360 2010-11-30            1
1556       59606 1994-12-31            1
1557       59606 1995-01-31            1
1558       60385 1990-04-30            1
1559       62226 2008-08-31            1
1560       62270 2004-04-30            1
1569       62270 2005-01-31            1
1570       63273 1988-12-31            1
1571       64013 1997-01-31            1
1632       64013 2002-02-28            1
1633       64123 1996-08-31            1
1678       64123 2000-05-31            1
1687       64123 2001-02-28            1
1714       64123 2003-05-31            1
1715       64246 2001-04-30            1
1716       65273 1992-07-31            1
1752       65273 1995-07-31            1
1753       66373 2012-03-31            1
1754       67264 2002-09-30            1
1755       67463 1989-01-31            1
1843       67463 1996-05-31            1
1849       67463 1996-11-30            1
1852       67463 1997-02-28            1
1859       67463 1997-09-30            1
1878       67463 1999-04-30            1
1897       67463 2000-11-30            1
1901       67463 2001-03-31            1
1926       67463 2003-04-30            1
1950       67463 2005-04-30            1
1951       67463 2005-05-31            1
1952       68413 2004-05-31            1
1953       70143 1993-09-30            1
1954       71400 2011-03-31            1
1955       72203 1990-08-31            1
1970       72203 1991-11-30            1
2073       72203 2000-06-30            1
2074       72335 2003-09-30            1
2075       72335 2003-10-31            1
2088       72335 2004-11-30            1
2089       72427 2002-05-31            1
2096       72427 2002-12-31            1
2097       72427 2003-01-31            2
2098       72427 2003-02-28            2
2099       72427 2003-03-31            2
2123       72427 2005-03-31            1
2175       72427 2009-07-31            2
2176       72480 1995-08-31            1
2259       72480 2002-07-31            1
2285       72480 2004-09-30            1
2305       72480 2006-05-31            1
2314       72480 2007-02-28            1
2315       72480 2007-03-31            1
2318       72480 2007-06-30            2
2319       72480 2007-07-31            1
2321       72480 2007-09-30            1
2323       72480 2007-11-30            1
2326       72480 2008-02-29            1
2329       72480 2008-05-31            1
2332       72480 2008-08-31            1
2333       72480 2008-09-30            1
2334       72480 2008-10-31            1
2335       74030 1997-11-30            1
2336       74030 1997-12-31            1
2339       74030 1998-03-31            1
2340       74223 1994-07-31            1
2341       74331 1998-11-30            1
2342       74456 2008-05-31            1
2343       77025 2002-06-30            1
2344       77375 2004-07-31            1
2345       77642 2004-02-29            1
2346       78601 2007-07-31            1
2347       79148 2003-07-31            1
2348       79210 1993-08-31            1
2349       81225 1989-12-31            1
2550       81225 2006-09-30            1
2551       81295 1998-07-31            1
2596       81295 2002-04-30            1
2636       81295 2005-08-31            1
2689       81295 2010-01-31            1
2691       81295 2010-03-31            1
2692       81295 2010-04-30            2
2696       81295 2010-08-31            1
2698       81295 2010-10-31            1
2702       81295 2011-02-28            1
2703       82534 2011-08-31            1
2704       83119 2005-10-31            1
2705       84264 1998-10-31            1
2766       84264 2003-11-30            1
2767       86339 1994-04-30            1
2894       86339 2004-11-30            1
2895       88056 2002-01-31            1
2896       89350 2005-11-30            1
2897       89401 2005-02-28            1
2898       89447 2001-06-30            1
2899       90050 1999-07-31            1
2900       90198 1990-04-30            1
2917       90198 1991-09-30            1
2961       90198 1995-05-31            1
2967       90198 1995-11-30            1
3012       90198 1999-08-31            1
3016       90198 1999-12-31            1
3127       90198 2009-03-31            1
3128       91089 1981-01-31            1
3129       91115 2000-05-31            1
3136       91115 2000-12-31            2
3199       91115 2006-03-31            1
3249       91115 2010-05-31            1
3250       91128 1991-08-31            1
3251       91412 2006-04-30            1
3252       93017 1993-01-31            1
3253       93206 2007-01-31            1
3254       93388 2007-06-30            1
3255       94496 2005-01-31            1
3270       94496 2006-04-30            1
3274       94496 2006-08-31            1
3332       94496 2011-06-30            1
3333       95446 1999-01-31            1
3334       95446 1999-02-28            1
3335       97521 2000-06-30            1
3336       99042 1998-02-28            1
3337       99196 2002-08-31            1
3338       99196 2002-09-30            1
3339       99571 2005-02-28            1
3340      100581 2012-07-31            2
3341      103329 2010-09-30            1
3342      104025 2005-06-30            1
3385      104025 2009-01-31            1
3386      105184 1989-01-31            1
3391      105184 1989-06-30            1
3393      105184 1989-08-31            1
3445      105184 1993-12-31            1
3473      105184 1996-04-30            1
3483      105184 1997-02-28            1
3490      105184 1997-09-30            1
3493      105184 1997-12-31            1
3500      105184 1998-07-31            1
3509      105184 1999-04-30            1
3589      105184 2005-12-31            1
3590      106283 2002-02-28            1
3603      106283 2003-03-31            1
3604      106448 2007-01-31            1
3631      106448 2009-04-30            1
3632      107617 2011-09-30            1
3633      107617 2011-10-31            1
3634      107617 2011-11-30            2
3635      108025 1997-08-31            1
3642      108025 1998-03-31            1
3664      108025 2000-01-31            1
3665      108027 2006-03-31            1
3666      109183 1996-01-31            3
3669      109183 1996-04-30            1
3701      109183 1998-12-31            1
3702      109323 2010-02-28            1
3703      109411 1992-08-31            2
3704      109411 1992-09-30            1
3706      109411 1992-11-30            1
3707      111115 1992-07-31            1
3710      111115 1992-10-31            1
3718      111115 1993-06-30            1
3733      111115 1994-09-30            1
3858      111115 2005-02-28            1
3859      112006 1973-01-31            1
3860      112569 2008-12-31            1
3861      113162 1997-11-30            1
3954      113162 2005-08-31            2
3955      114061 2006-03-31            1
3956      114163 1999-11-30            1
3957      114200 2007-08-31            2
3958      116063 1999-08-31            1
4054      116063 2007-08-31            1
4055      118556 2006-06-30            1
4056      119412 2003-04-30            1
4057      120116 1991-05-31            1
4060      120116 1991-08-31            1
4094      120116 1994-06-30            1
4097      120116 1994-09-30            1
4102      120116 1995-02-28            1
4103      120116 1995-03-31            1
4104      120511 2005-07-31            1
4160      120511 2010-03-31            1
4161      123084 1992-08-31            1
4171      123084 1993-06-30            1
4172      124004 1991-04-30            1
4173      124416 1994-10-31            1
4174      126092 1991-01-31            1
4175      126113 2002-01-31            1
4176      126113 2002-02-28            1
4177      126113 2002-03-31            1
4178      126113 2002-04-30            3
4179      126113 2002-05-31            1
4181      126113 2002-07-31            1
4182      127378 2007-06-30            1
4183      127446 2001-02-28            1
4242      127446 2006-01-31            1
4262      127446 2007-09-30            1
4299      127446 2010-10-31            1
4306      127446 2011-05-31            1
4321      127446 2012-08-31            1
4328      127446 2013-03-31            1
4329      127496 2009-05-31            1
4330      127601 2008-08-31            1
4331      128163 1999-12-31            2
4332      128602 1997-09-30            1
4333      129092 2005-10-31            1
4334      129525 1995-04-30            1
4335      130006 1970-01-31            1
4336      133277 2011-05-31            2
4337      134322 1992-04-30            1
4338      135063 2009-01-31            1
4339      135202 1993-01-31            1
4353      135202 1994-03-31            1
4370      135202 1995-08-31            1
4379      135202 1996-05-31            1
4384      135202 1996-10-31            1
4413      135202 1999-03-31            1
4445      135202 2001-11-30            1
4471      135202 2004-01-31            1
4472      136059 2000-04-30            1
4480      136059 2000-12-31            1
4481      137147 2005-03-31            1
4484      137147 2005-06-30            1
4485      140320 1990-01-31            1
4498      140320 1991-02-28            1
4509      140320 1992-01-31            1
4519      140320 1992-11-30            1
4643      140320 2003-03-31            1
4644      142093 2007-10-31            1
4645      142495 2006-08-31            1
4646      144447 2008-07-31            2
4657      144447 2009-06-30            1
4658      144454 2010-10-31            1
4659      145571 2009-06-30            1
4660      146093 1989-05-31            2
4661      146093 1989-06-30            1
4666      146093 1989-11-30            1
4670      146093 1990-03-31            1
4678      146093 1990-11-30            1
4680      146093 1991-01-31            1
4681      147290 1996-01-31            1
4701      147290 1997-09-30            1
4704      147290 1997-12-31            1
4708      147290 1998-04-30            1
4709      149001 1989-11-30            1
4710      149379 2004-04-30            1
4711      150557 2005-12-31            1
4725      150557 2007-02-28            1
4726      151017 1983-01-31            1
4727      151228 1988-05-31            1
4728      152447 1992-08-31            1
4739      152447 1993-07-31            1
4743      152447 1993-11-30            1
4761      152447 1995-05-31            1
4779      152447 1996-11-30            1
4810      152447 1999-06-30            1
4840      152447 2001-12-31            1
4869      152447 2004-05-31            1
4887      152447 2005-11-30            1
4888      154179 2000-10-31            1
4889      154454 1994-08-31            1
4890      154589 2001-01-31            1
4891      154589 2001-02-28            1
4892      155159 1992-02-29            1
5051      155159 2005-05-31            1
5052      157098 1999-08-31            1
5064      157098 2000-08-31            1
5065      157099 1989-01-31            1
5066      157536 2000-12-31            1
5067      159490 2000-08-31            1
5068      161017 1996-02-29            1
5085      161017 1997-07-31            1
5086      162158 2005-09-30            1
5087      162279 1991-10-31            1
5088      162452 1988-10-31            1
5089      163289 2006-07-31            1
5090      164447 1996-06-30            1
5091      165233 2008-05-31            1
5092      166210 1966-01-31            1
5093      166256 2001-01-31            1
5094      167229 1993-04-30            1
5111      167229 1994-09-30            1
5112      170025 1990-11-30            1
5117      170025 1991-04-30            1
5221      170025 1999-12-31            1
5222      170601 2002-03-31            1
5223      170601 2002-04-30            1
5266      170601 2005-11-30            1
5267      171052 2010-09-30            1
5268      171450 1998-03-31            1
5283      171450 1999-06-30            1
5284      171450 1999-07-31            2
5285      172166 2005-04-30            1
5308      172166 2007-03-31            1
5309      173066 2003-10-31            1
5310      173251 2007-02-28            1
5311      174018 2007-12-31            1
5312      174194 2002-01-31            1
5325      174194 2003-02-28            1
5341      174194 2004-06-30            1
5342      174614 1995-10-31            1
5343      175140 2001-06-30            1
5344      177476 2003-11-30            1
5345      178168 2006-02-28            1
5346      179091 1991-04-30            1
5347      179091 1991-05-31            1
5368      179091 1993-02-28            1
5386      179091 1994-08-31            1
5400      179091 1995-10-31            1
5401      179091 1995-11-30            1
5405      179091 1996-03-31            2
5416      179091 1997-02-28            1
5418      179091 1997-04-30            1
5421      179091 1997-07-31            1
5423      179091 1997-09-30            1
5432      179091 1998-06-30            1
5478      179091 2002-04-30            2
5479      179091 2002-05-31            1
5481      179091 2002-07-31            2
5484      179091 2002-10-31            2
5486      179091 2002-12-31            2
5487      179091 2003-01-31            3
5489      179091 2003-03-31            1
5499      179091 2004-01-31            1
5500      179091 2004-02-29            1
5507      179091 2004-09-30            1
5510      179091 2004-12-31            1
5511      179091 2005-01-31            2
5515      179091 2005-05-31            1
5516      179091 2005-06-30            1
5541      179091 2007-07-31            1
5542      179115 1994-10-31            1
5543      179320 2001-01-31            1
5606      179320 2006-04-30            1
5664      179320 2011-02-28            1
5678      179320 2012-04-30            1
5679      179447 2008-02-29            1
5680      180458 1998-01-31            1
5681      181023 1960-04-30            1
5682      181393 2006-11-30            1
5711      181393 2009-04-30            1
5725      181393 2010-06-30            1
5726      182174 1990-04-30            1
5750      182174 1992-04-30            1
5752      182174 1992-06-30            1
5753      182174 1992-07-31            1
5883      182174 2003-05-31            1
5884      182280 2012-01-31            1
5885      182437 1995-09-30            1
5886      182437 1995-10-31            1
5887      183088 2008-10-31            1
5888      183088 2008-11-30            1
5889      183263 2003-11-30            1
5890      183447 2003-09-30            1
5932      183447 2007-03-31            1
5942      183447 2008-01-31            1
5953      183447 2008-12-31            1
5954      183447 2009-01-31            1

In [40]:
pt_features = pd.read_csv('data/pt_data/pt_features.csv',delimiter=',',parse_dates=['index_date'],infer_datetime_format=True)

In [41]:
pt_features.head(3)

,patid,pracid,gender,birthyear,index_date,isCase,final dementia medcode,final dementia read term,data_start,data_end,days pre_indexdate,days post_indexdate,matchid,total_available_data
0,21880670,670,2,1931,2009-03-30,True,6578.0,[X]Vascular dementia,1999-04-02,2013-04-04,3650.0,1466.0,787.0,5116 days 00:00:00.000000000
1,3846066,66,2,1931,2009-12-10,True,8195.0,[X]Alzheimer's dementia unspec,1999-12-13,2011-12-28,3650.0,748.0,1522.0,4398 days 00:00:00.000000000
2,2904565,565,2,1943,2009-03-12,True,37014.0,[X]Dementia in Huntington's disease,1999-03-15,2013-04-12,3650.0,1492.0,3342.0,5142 days 00:00:00.000000000

In [42]:
insom_events = pd.merge(insom_events,pt_features,how='inner')[['patid','eventdate','insom_count','index_date']]

In [44]:
insom_events.head(20)

    patid  eventdate  insom_count index_date
0   12043 1990-02-28            1 2010-09-22
1   24081 1991-03-31            1 2010-06-23
2   24081 1997-06-30            1 2010-06-23
3   37099 2001-04-30            1 2005-12-12
4   39463 1989-01-31            1 2007-11-09
5   39463 1993-06-30            1 2007-11-09
6   39463 1995-07-31            1 2007-11-09
7   39463 1996-08-31            1 2007-11-09
8   39463 1999-07-31            1 2007-11-09
9   39463 1999-09-30            1 2007-11-09
10  39463 2001-04-30            1 2007-11-09
11  39463 2004-12-31            1 2007-11-09
12  39463 2007-11-30            4 2007-11-09
13  39463 2007-12-31            1 2007-11-09
14  39463 2008-03-31            1 2007-11-09
15  44447 1996-10-31            1 2010-03-01
16  44447 1997-10-31            1 2010-03-01
17  44447 2002-12-31            1 2010-03-01
18  44447 2008-02-29            1 2010-03-01
19  44447 2008-05-31            1 2010-03-01

In [45]:
interim_period = timedelta(days=365)*Study_Design.years_between_end_of_exposure_period_and_index_date

In [62]:
relevant_event_mask = (insom_events['eventdate']<=(insom_events['index_date']-interim_period)) & (insom_events['eventdate']>=(insom_events['index_date']-timedelta(days=365)*Study_Design.total_years_required_pre_index_date))

In [69]:
insom_events = insom_events.loc[relev_insom_events]

In [71]:
insom_events.head(5)

    patid  eventdate  insom_count index_date
2   24081 1997-06-30            1 2010-06-23
5   39463 1993-06-30            1 2007-11-09
6   39463 1995-07-31            1 2007-11-09
7   39463 1996-08-31            1 2007-11-09
15  44447 1996-10-31            1 2010-03-01

In [74]:
insom_events.groupby('patid')['insom_count'].count().reset_index()

        patid  insom_count
0       24081            1
1       39463            3
2       44447            2
3       72203            1
4       81295            1
5      129525            1
6      179091            5
7      239323            2
8      271483            1
9      293043            3
10     329622            3
11     375259            1
12     396202            1
13     403221            1
14     415128            1
15     425047            4
16     435115            4
17     471250            1
18     501051            1
19     510206            1
20     536270            1
21     554013            1
22     556163            4
23     595155            1
24     680335            2
25     681319            1
26     732127            1
27     733257            1
28     747436            1
29     758409            1
30     864250            3
31     890031            1
32     905115            3
33     957309            1
34     960047            4
35    1040215            3
36    1043447            1
37    1045323            1
38    1095155            1
39    1113250            6
40    1113657            2
41    1165409            1
42    1207323            1
43    1315255            1
44    1333309            1
45    1353250            2
46    1375357            1
47    1396115            1
48    1409447            1
49    1426325            1
50    1483024            4
51    1501028            2
52    1530472            1
53    1562336            1
54    1570199            2
55    1636288            5
56    1675159            1
57    1681323            3
58    1784051            6
59    1798156            4
60    1855013            2
61    1900270            1
62    1952463            1
63    1962323            1
64    2055444            1
65    2064021            1
66    2101270            5
67    2119290            1
68    2121017            2
69    2136115            1
70    2140163            1
71    2170353            1
72    2233028            1
73    2235284            1
74    2359339            2
75    2373056            1
76    2379472            1
77    2400089            1
78    2412525            1
79    2416321            3
80    2476043            1
81    2479303            1
82    2502460            1
83    2560099           13
84    2570452            1
85    2613071            1
86    2615441            1
87    2620058            1
88    2631588            1
89    2632091            1
90    2646156            1
91    2666323            1
92    2746093            2
93    2759013            2
94    2789081            1
95    2872017            1
96    2898202            1
97    2925093            1
98    2936182            1
99    2938450            5
100   2951099            2
101   2982606            1
102   3017325            2
103   3025054            1
104   3043331            1
105   3046115            1
106   3073321            1
107   3112215            2
108   3191206            1
109   3223330            2
110   3237171            1
111   3343454            2
112   3368163            1
113   3423263            1
114   3433017            1
115   3433051            1
116   3441249            3
117   3446429            1
118   3474409            1
119   3606155            1
120   3610323            1
121   3623021            1
122   3659407            4
123   3665071            1
124   3683234            1
125   3691174            5
126   3730323            1
127   3742322            1
128   3764051            2
129   3847447            3
130   3851431            1
131   3865024            1
132   3901290            1
133   3909084            1
134   3915250            1
135   3936202            1
136   3943436            1
137   3979171            2
138   4029017            1
139   4039099            1
140   4059157            1
141   4067099            1
142   4070226            1
143   4091115            1
144   4102174            2
145   4124193            6
146   4131023            1
147   4162586            2
148   4169447            8
149   4171525            1
150   4291263            1
151   4307331            1
152   4323081            1
153   4340021            1
154   4365263            2
155   4495331            1
156   4498137           12
157   4515331            1
158   4518486            1
159   4587344            3
160   4624162            1
161   4673434            1
162   4691038            2
163   4763059            1
164   4764250            8
165   4845171            2
166   4875270            3
167   4929021            1
168   4937051            1
169   4980156            1
170   5114043            2
171   5114196            1
172   5118031            2
173   5143344            1
174   5178288            1
175   5190404            1
176   5201043            2
177   5219182            1
178   5273155            1
179   5363199            1
180   5376295            4
181   5381081            1
182   5442031            1
183   5488438            3
184   5522031            1
185   5550157            1
186   5569438            2
187   5629038            8
188   5658343            1
189   5690093            1
190   5732031            1
191   5755099            1
192   5842194            5
193   5849178            1
194   5911320            1
195   5949088            4
196   5957225            1
197   5958410            1
198   6049031            1
199   6079115            4
200   6113164            1
201   6194024            1
202   6209155            1
203   6238081            1
204   6279202            4
205   6289051            2
206   6291196            1
207   6304081            1
208   6336043            2
209   6360021            1
210   6510295            2
211   6518093            1
212   6523194            2
213   6762193           14
214   6770438            1
215   6870155            1
216   6906174            3
217   6907115            2
218   6933456            1
219   6938081            4
220   6949404            1
221   6967325            1
222   6980013            1
223   7018088            1
224   7129483            1
225   7136288            2
226   7142084            2
227   7232319            3
228   7250158            3
229   7268552            1
230   7282199            1
231   7289320            1
232   7373483            1
233   7519282            1
234   7607184            3
235   7667429            1
236   7683322           15
237   7715293            1
238   7750315            3
239   7780093            1
240   7817263            1
241   7824378            2
242   7859206            1
243   7878031            2
244   7916155            2
245   7920001            1
246   7925225            1
247   7951137            3
248   7954344            2
249   7957456            1
250   7963359            1
251   8011434            1
252   8061155            1
253   8062606            3
254   8170051            1
255   8179155            1
256   8351314            1
257   8410225            3
258   8471031            2
259   8511314            2
260   8675021            1
261   8717270            2
262   8719137            1
263   8849378            1
264   8910038            2
265   8965174            2
266   9087013            1
267   9246398            1
268   9259319            1
269   9260434            1
270   9319411            1
271   9586115            8
272   9604024            1
273   9782024            1
274   9826398            2
275   9869429            2
276   9886115            1
277   9896391            3
278   9953031            1
279  10082021            1
280  10094314            1
281  10212031            1
282  10294379            1
283  10448059            2
284  10452441            2
285  10533429            1
286  10601670            1
287  10702006            2
288  10727606            1
289  10747155            4
290  10803155            1
291  10861109            1
292  10972410            1
293  11038154            1
294  11303043            2
295  11418184            1
296  11455205            2
297  11465450            1
298  11607438            3
299  11629089            1
300  11660043            1
301  11749586            1
302  11756344            3
303  11845088            2
304  11939255            2
305  11945031            5
306  12248147            1
307  12471244            2
308  12553081            1
309  12585330           10
310  12949081            1
311  13023606            1
312  13030088            1
313  13132190            1
314  13145154            1
315  13368606            1
316  13392155            1
317  13564002            1
318  13738319            1
319  13974081            1
320  14123398            1
321  14442123            1
322  14469205            4
323  14565244            1
324  14657470            2
325  14684670            1
326  14899031            5
327  15331344            1
328  15491270            9
329  15683005            1
330  15695205            3
331  15989404            1
332  16016051            3
333  16047427            1
334  16177013            1
335  16487031            1
336  16535088            1
337  16963463            1
338  17522030            1
339  17581438            2
340  17666391            2
341  17683407            1
342  17954038            1
343  18057463            3
344  18066013            1
345  18340013            5
346  18625013            1
347  18681295            1
348  18852182            1
349  18882306            1
350  19226223            1
351  19317319            1
352  19942366            3
353  20142043            1
354  20579088            2
355  20608013            2
356  20786438            1
357  21070229            1
358  21642306            1
359  21917670            1
360  23198404            1
361  23234088            1
362  24094002            1
363  24207229            2
364  24433120            1
365  27931088            1
366  30263470            1
367  41315229            1
368  44482229            1
369  45201465            1
370  46040229            2

In [76]:
pt_features = pd.merge(pt_features,insom_events,how='left')

In [78]:
pt_features['insom_count'].fillna(0,inplace=True)

In [81]:
pt_features['insom_count'] = pt_features['insom_count'].astype(int)

In [83]:
pt_features

         patid  pracid  gender  birthyear index_date isCase  \
0     21880670     670       2       1931 2009-03-30   True
1      3846066      66       2       1931 2009-12-10   True
2      2904565     565       2       1943 2009-03-12   True
3      4537438     438       2       1939 2006-11-01   True
4      5924670     670       2       1935 2009-03-30   True
5      2859159     159       2       1927 2007-07-25   True
6     44248465     465       2       1935 2009-08-08   True
7      2245225     225       2       1933 2006-06-19   True
8      4628670     670       1       1927 2009-03-31   True
9      1829651     651       1       1921 2009-05-22   True
10    18325166     166       1       1931 2010-04-09   True
11     2075651     651       1       1935 2009-05-22   True
12     2963565     565       2       1924 2009-03-13   True
13    10139343     343       2       1922 2005-09-14   True
14     3672412     412       1       1934 2010-11-22   True
15     3433051      51       2       1929 2007-01-18   True
16     3014472     472       2       1927 2009-10-19   True
17     2740035      35       2       1927 2009-05-20   True
18    10398005       5       1       1933 2007-11-22   True
19     6715251     251       2       1929 2009-01-27   True
20     3035097      97       2       1927 2009-07-09   True
21     4207149     149       2       1920 2007-02-06   True
22     6238412     412       1       1928 2010-11-23   True
23     4971257     257       1       1927 2006-11-14   True
24    19393089      89       1       1923 2007-07-27   True
25     3642066      66       2       1921 2009-12-14   True
26     3012078      78       2       1920 2009-09-11   True
27    17267628     628       1       1930 2008-11-17   True
28     4538446     446       2       1923 2010-07-30   True
29     2651017      17       1       1916 2008-04-21   True
30    19641002       2       1       1935 2009-09-03   True
31     5633670     670       2       1922 2009-04-05   True
32     5318098      98       2       1920 2006-05-25   True
33     7255657     657       2       1931 2006-09-26   True
34     1037056      56       2       1923 2006-08-10   True
35    11337270     270       1       1927 2005-12-16   True
36     3719129     129       2       1917 2006-10-16   True
37    15099244     244       1       1929 2010-07-02   True
38     5169138     138       2       1930 2006-11-08   True
39     8191262     262       2       1924 2007-02-15   True
40     1511127     127       1       1932 2007-03-31   True
41    10978005       5       2       1927 2007-11-27   True
42     9541651     651       1       1926 2009-05-29   True
43     1464384     384       1       1921 2009-10-27   True
44     2214339     339       2       1934 2010-10-01   True
45      753413     413       1       1924 2009-10-27   True
46     2716323     323       2       1933 2007-02-02   True
47     6033246     246       1       1934 2008-07-09   True
48    10190104     104       2       1920 2011-03-21   True
49    18013180     180       2       1934 2010-06-28   True
50     7023201     201       1       1925 2007-06-06   True
51     9478323     323       1       1932 2007-02-02   True
52     2228380     380       2       1928 2010-10-27   True
53    18990003       3       1       1921 2011-02-27   True
54      989047      47       1       1926 2007-07-02   True
55     1031023      23       1       1924 2007-08-07   True
56     9945466     466       2       1931 2010-12-21   True
57     6778045      45       2       1925 2009-07-02   True
58     3552620     620       2       1924 2009-03-18   True
59     9792114     114       2       1923 2010-12-07   True
60     9890091      91       2       1930 2005-08-26   True
61      123201     201       2       1924 2007-06-08   True
62     2362383     383       1       1926 2006-03-14   True
63    17338154     154       2       1920 2006-08-24   True
64    22592120     120       2       1925 2005-12-21   True
65     7790002       2       2       1943 2009-09-10   True
66     4137205     205       1       1924 2009-12-24   True
67     5010331     331       1       1919 2006-05-14   True
68     8223194     194       2       1920 2006-08-21   True
69      560391     391       2       1920 2007-06-08   True
70    14969257     257       1       1931 2008-10-18   True
71     9315482     482       1       1932 2009-11-30   True
72     2434371     371       2       1931 2009-03-25   True
73     1636288     288       2       1923 2009-09-15   True
74     1636288     288       2       1923 2009-09-15   True
75     1636288     288       2       1923 2009-09-15   True
76     1636288     288       2       1923 2009-09-15   True
77     1636288     288       2       1923 2009-09-15   True
78    10681023      23       2       1927 2007-08-13   True
79     2509256     256       2       1925 2009-07-28   True
80     1715184     184       2       1933 2010-09-20   True
81     1358454     454       1       1926 2007-08-14   True
82    12659427     427       1       1938 2005-09-15   True
83     5148598     598       2       1932 2009-12-22   True
84    10584321     321       2       1918 2006-04-19   True
85     4360668     668       2       1928 2009-12-07   True
86     1306409     409       2       1918 2008-09-30   True
87      718011      11       1       1925 2011-03-04   True
88     7607184     184       2       1925 2010-09-21   True
89     7607184     184       2       1925 2010-09-21   True
90     7607184     184       2       1925 2010-09-21   True
91     4008201     201       2       1924 2007-06-15   True
92     3946003       3       1       1924 2011-03-08   True
93    11880476     476       1       1928 2009-10-01   True
94    19775396     396       1       1936 2011-03-23   True
95      345230     230       2       1932 2008-04-09   True
96    10247020      20       2       1933 2009-10-15   True
97    11333166     166       2       1943 2010-04-26   True
98    13395148     148       1       1922 2006-11-15   True
99    30728002       2       2       1919 2011-02-01   True
100    1787476     476       1       1920 2009-10-02   True
101    5022483     483       1       1931 2006-07-20   True
102    1454064      64       1       1927 2010-08-03   True
103   13214002       2       2       1930 2009-09-16   True
104     926243     243       2       1929 2009-10-06   True
105    9689212     212       1       1927 2009-11-11   True
106   11455205     205       2       1923 2009-12-30   True
107   11455205     205       2       1923 2009-12-30   True
108   12471244     244       2       1936 2010-03-22   True
109   12471244     244       2       1936 2010-03-22   True
110    9793064      64       2       1922 2011-02-18   True
111    2900530     530       1       1920 2009-09-25   True
112   22703670     670       2       1934 2009-04-20   True
113    7232427     427       1       1938 2005-09-21   True
114    8134282     282       2       1925 2009-04-27   True
115    3641446     446       2       1926 2010-08-17   True
116    6655371     371       1       1927 2009-04-01   True
117   11855309     309       2       1935 2007-06-07   True
118    2456017      17       1       1920 2008-05-08   True
119   11751059      59       2       1914 2006-07-07   True
120    4067099      99       2       1914 2005-10-03   True
121   27312670     670       1       1934 2009-04-23   True
122    3974321     321       2       1913 2006-04-26   True
123    8351206     206       2       1924 2009-05-12   True
124   35623088      88       1       1932 2007-06-29   True
125    6925319     319       1       1932 2005-10-28   True
126    5679409     409       2       1927 2008-10-08   True
127    1614149     149       2       1926 2006-06-16   True
128      16043      43       2       1922 2006-01-27   True
129     912456     456       2       1922 2006-12-15   True
130   13557189     189       2       1933 2009-12-16   True
131     570243     243       2       1925 2009-10-13   True
132    7211178     178       1       1939 2009-01-07   True
133    9674199     199       2       1920 2006-06-06   True
134    5594249     249       1       1925 2010-06-09   True
135    7269653     653       2       1928 2007-06-05   True
136    1962193     193       1       1923 2007-12-10   True
137     117011      11       2       1926 2011-03-15   True
138    1475653     653       2       1923 2007-06-06   True
139   11119295     295       1       1930 2006-06-29   True
140    1092447     447       1       1930 2010-01-10   True
141   12207091      91       2       1926 2005-09-13   True
142    3839132     132       1       1930 2010-10-12   True
143    3791113     113       1       1926 2006-01-10   True
144    3035132     132       1       1941 2010-10-13   True
145     310200     200       1       1930 2011-01-18   True
146    6880486     486       2       1927 2010-01-01   True
147    8719137     137       2       1929 2008-12-15   True
148    3847349     349       2       1933 2009-11-11   True
149    7817263     263       2       1934 2009-12-23   True
150    4771249     249       2       1932 2010-06-16   True
151   14400066      66       2       1923 2010-01-13   True
152   29677088      88       1       1920 2006-07-10   True
153     849349     349       2       1915 2009-11-12   True
154    3504504     504       2       1927 2007-06-27   True
155    1213128     128       2       1920 2009-12-21   True
156    2269054      54       1       1928 2009-12-21   True
157   11684264     264       1       1934 2006-06-27   True
158   57590229     229       1       1926 2010-02-09   True
159   13906244     244       1       1922 2010-04-06   True
160    9280003       3       1       1922 2011-03-26   True
161    4919293     293       2       1919 2007-07-23   True
162    4112310     310       2       1928 2007-11-19   True
163    6596227     227       1       1925 2005-11-08   True
164    3135271     271       2       1928 2009-10-26   True
165     682670     670       2       1921 2009-05-06   True
166    7671001       1       2       1918 2007-04-12   True
167    5201283     283       1       1916 2006-04-24   True
168    7713384     384       2       1925 2009-11-26   True
169   11776157     157       1       1924 2010-11-12   True
170    8431085      85       2       1929 2009-10-28   True
171    4387284     284       1       1927 2007-07-18   True
172     950421     421       2       1929 2010-08-24   True
173   18879270     270       2       1925 2006-01-17   True
174    6587651     651       2       1939 2009-06-30   True
175     984163     163       2       1926 2006-01-04   True
176    2575115     115       2       1924 2006-04-10   True
177    6974409     409       1       1926 2008-10-24   True
178    1570651     651       2       1934 2009-07-01   True
179   10292003       3       2       1944 2011-03-31   True
180    3963436     436       2       1930 2009-09-10   True
181    1172471     471       1       1919 2007-01-01   True
182    7142084      84       2       1919 2010-01-18   True
183    7142084      84       2       1919 2010-01-18   True
184    6907115     115       2       1928 2006-04-12   True
185    6907115     115       2       1928 2006-04-12   True
186    9450021      21       2       1926 2008-10-27   True
187    4428263     263       2       1923 2010-01-01   True
188    7893003       3       2       1933 2011-04-01   True
189    8200471     471       1       1928 2007-01-01   True
190    7073407     407       2       1917 2006-07-20   True
191    4316003       3       2       1930 2011-04-02   True
192    7741196     196       1       1938 2008-05-01   True
193   10157520     520       2       1928 2010-01-11   True
194    4115059      59       2       1924 2006-07-26   True
195    1702452     452       2       1926 2009-11-03   True
196    8658035      35       1       1923 2009-06-30   True
197    9448463     463       2       1923 2006-01-23   True
198    5949088      88       1       1932 2006-07-20   True
199    5949088      88       1       1932 2006-07-20   True
200    5949088      88       1       1932 2006-07-20   True
201    5949088      88       1       1932 2006-07-20   True
202    2667196     196       1       1927 2008-05-02   True
203    3273359     359       1       1932 2007-05-24   True
204    7479162     162       2       1923 2006-05-25   True
205    2448353     353       1       1925 2009-10-26   True
206    3616275     275       1       1931 2009-12-15   True
207    1092460     460       2       1925 2009-12-31   True
208    5041330     330       2       1922 2010-05-05   True
209    1725309     309       2       1929 2007-06-30   True
210    8089200     200       1       1935 2011-02-01   True
211    5030006       6       2       1928 2010-01-18   True
212    6987194     194       2       1926 2006-09-22   True
213   38172670     670       2       1942 2010-12-07   True
214    5841148     148       1       1921 2007-05-01   True
215    7266438     438       2       1927 2006-12-18   True
216     529153     153       2       1926 2010-05-05   True
217    1258325     325       1       1922 2008-01-31   True
218   10019345     345       2       1922 2010-08-06   True
219    2702624     624       2       1921 2010-06-25   True
220    4994365     365       1       1921 2009-03-27   True
221   14464027      27       1       1916 2008-01-14   True
222    1673335     335       1       1935 2010-10-22   True
223   16812407     407       1       1928 2006-07-27   True
224    3032200     200       2       1926 2011-02-04   True
225    3459020      20       2       1924 2006-03-21   True
226   16201410     410       2       1933 2007-05-14   True
227   13023606     606       2       1928 2009-11-24   True
228     956411     411       2       1928 2006-10-03   True
229    7412606     606       2       1924 2009-11-24   True
230     766359     359       1       1938 2009-01-12   True
231    4347617     617       2       1931 2007-10-02   True
232    1737240     240       1       1935 2009-11-02   True
233    2117148     148       2       1926 2006-11-27   True
234    7223154     154       2       1924 2006-10-02   True
235     479271     271       2       1943 2009-11-09   True
236     372297     297       2       1925 2006-01-01   True
237    2503459     459       2       1929 2010-01-20   True
238    4027435     435       1       1926 2009-11-17   True
239     927240     240       2       1933 2009-11-03   True
240    1545655     655       2       1935 2010-01-28   True
241   12346398     398       2       1921 2008-01-17   True
242    4928309     309       2       1923 2007-07-06   True
243    1681459     459       2       1930 2010-01-20   True
244    5280613     613       1       1929 2009-01-20   True
245   21070229     229       2       1920 2006-03-23   True
246     272409     409       2       1923 2008-11-05   True
247    5352117     117       2       1931 2006-10-18   True
248    8726234     234       2       1925 2010-01-20   True
249      73013      13       2       1933 2005-09-16   True
250    2783053      53       1       1922 2010-01-14   True
251    2484325     325       2       1926 2008-02-07   True
252    6426223     223       1       1926 2009-03-17   True
253    8228651     651       2       1922 2009-07-14   True
254    1608441     441       2       1928 2007-10-19   True
255   11110190     190       2       1931 2008-03-28   True
256    4667427     427       2       1921 2005-10-24   True
257   13125251     251       2       1932 2009-04-09   True
258     568002       2       2       1925 2009-10-23   True
259   15695205     205       2       1937 2010-02-04   True
260   15695205     205       2       1937 2010-02-04   True
261   15695205     205       2       1937 2010-02-04   True
262    3624552     552       2       1943 2010-02-01   True
263   10756191     191       2       1936 2011-04-01   True
264     593164     164       1       1926 2006-07-07   True
265    8483184     184       1       1938 2010-10-31   True
266     308573     573       2       1923 2007-08-28   True
267     479565     565       2       1921 2009-05-08   True
268     155159     159       2       1932 2007-09-20   True
269     374025      25       1       1920 2010-06-22   True
270    2533247     247       2       1914 2007-06-06   True
271   14314319     319       2       1920 2005-11-30   True
272     657128     128       2       1925 2010-01-13   True
273    4829512     512       1       1937 2010-02-01   True
274    4271463     463       1       1928 2006-02-06   True
275    8690520     520       2       1922 2010-01-27   True
276    7659434     434       2       1931 2006-06-30   True
277    1094269     269       2       1934 2010-07-07   True
278   12415027      27       2       1930 2008-01-24   True
279   12031343     343       2       1926 2005-11-11   True
280   12324145     145       2       1935 2010-11-08   True
281    6952335     335       2       1929 2010-11-02   True
282    9826398     398       2       1926 2008-01-25   True
283    9826398     398       2       1926 2008-01-25   True
284   10011606     606       2       1927 2009-12-04   True
285   11553330     330       2       1937 2010-05-19   True
286   11062460     460       1       1930 2010-01-14   True
287    2808325     325       2       1926 2008-02-14   True
288    5629038      38       2       1930 2005-09-26   True
289    5629038      38       2       1930 2005-09-26   True
290    5629038      38       2       1930 2005-09-26   True
291    5629038      38       2       1930 2005-09-26   True
292    5629038      38       2       1930 2005-09-26   True
293    5629038      38       2       1930 2005-09-26   True
294    5629038      38       2       1930 2005-09-26   True
295    5629038      38       2       1930 2005-09-26   True
296    3424435     435       1       1933 2009-11-26   True
297    7853438     438       2       1918 2007-01-01   True
298    2354438     438       2       1927 2007-01-01   True
299    7082002       2       2       1927 2010-12-14   True
300    5770484     484       1       1939 2010-01-01   True
301    1570199     199       1       1928 2006-07-11   True
302    1570199     199       1       1928 2006-07-11   True
303    7225447     447       2       1916 2010-02-12   True
304    6492127     127       2       1920 2007-05-24   True
305    8296657     657       1       1920 2006-11-22   True
306     621397     397       2       1937 2005-05-16   True
307    3070243     243       2       1935 2009-11-19   True
308    8135398     398       2       1918 2008-01-29   True
309   15561460     460       1       1935 2010-01-18   True
310    4779145     145       1       1930 2010-11-12   True
311   17145158     158       2       1927 2010-10-01   True
312   10520606     606       2       1930 2009-12-08   True
313     655020      20       2       1919 2006-04-05   True
314   31497470     470       2       1918 2007-04-01   True
315    6723371     371       2       1930 2009-05-13   True
316     211338     338       1       1925 2005-11-09   True
317    2326658     658       2       1935 2007-08-02   True
318    2552024      24       1       1922 2008-01-03   True
319    6287483     483       2       1925 2006-09-05   True
320    1752153     153       2       1929 2010-05-24   True
321   13956383     383       2       1918 2009-06-03   True
322    3796444     444       1       1927 2006-07-11   True
323    3967325     325       1       1933 2008-02-20   True
324   11685343     343       2       1921 2005-11-18   True
325    4057205     205       2       1921 2010-02-16   True
326    5136154     154       1       1926 2006-10-19   True
327    4318263     263       2       1920 2010-01-27   True
328   17193190     190       2       1919 2008-04-10   True
329    7671191     191       1       1924 2011-04-13   True
330    5550157     157       2       1921 2006-04-27   True
331   18681407     407       1       1918 2006-08-17   True